name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Install env
        run: sudo apt-get install flex bison
      - name: clean
        working-directory: spl_project3
        run: rm -rf ./bin/*
      - name: cmake .
        working-directory: spl_project3
        run: make
